/*
 * File: app/controller/QuestionController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.QuestionController', {
    extend: 'Ext.app.Controller',
    config: {
    },

    init: function(application) {
        var me = this;
        Ext.Viewport.setMasked({ message: 'Laster spørsmål...' });
        // get the question... {
        me.getQuestion(id, function (store) {
            // then bind data to list and show it
            me.getDataList().setStore(store);
            Ext.Viewport.setMasked(false);
        });
    }

});