/*
 * File: app/view/MyCarousel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyCarousel', {
    extend: 'Ext.carousel.Carousel',

    config: {
        id: 'carousel',
        items: [
            {
                xtype: 'formpanel',
                id: 'question1Panel',
                items: [
                    {
                        xtype: 'label',
                        height: 70,
                        html: 'Spørsmål 1',
                        id: 'questionTitle',
                        styleHtmlContent: true,
                        ui: 'light',
                        width: 285
                    },
                    {
                        xtype: 'fieldset',
                        id: 'questionContainer',
                        title: 'Bla bla bla bla bla bla bla?',
                        items: [
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans1',
                                label: ' 2000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans2',
                                label: ' 9000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans3',
                                label: ' 20000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans4',
                                label: ' 800000',
                                labelWidth: 200
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                maxWidth: '',
                                width: 100,
                                text: '<'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                maxWidth: '',
                                width: 100,
                                text: '>'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                id: 'question2Panel',
                items: [
                    {
                        xtype: 'label',
                        height: 70,
                        html: 'Spørsmål 2',
                        id: 'questionTitle',
                        styleHtmlContent: true,
                        ui: 'light',
                        width: 285
                    },
                    {
                        xtype: 'fieldset',
                        id: 'questionContainer',
                        title: 'Bla bla bla bla bla bla bla?',
                        items: [
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans1',
                                label: ' 2000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans2',
                                label: ' 9000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans3',
                                label: ' 20000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans4',
                                label: ' 800000',
                                labelWidth: 200
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                maxWidth: '',
                                width: 100,
                                text: '<'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                maxWidth: '',
                                width: 100,
                                text: '>'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                id: 'question3Panel',
                items: [
                    {
                        xtype: 'label',
                        height: 70,
                        html: 'Spørsmål 3',
                        id: 'questionTitle',
                        styleHtmlContent: true,
                        ui: 'light',
                        width: 285
                    },
                    {
                        xtype: 'fieldset',
                        id: 'questionContainer',
                        title: 'Bla bla bla bla bla bla bla?',
                        items: [
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans1',
                                label: ' 2000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans2',
                                label: ' 9000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans3',
                                label: ' 20000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans4',
                                label: ' 800000',
                                labelWidth: 200
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                maxWidth: '',
                                width: 100,
                                text: '<'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                maxWidth: '',
                                width: 100,
                                text: '>'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                id: 'question4Panel',
                items: [
                    {
                        xtype: 'label',
                        height: 70,
                        html: 'Spørsmål 1',
                        id: 'questionTitle',
                        styleHtmlContent: true,
                        ui: 'light',
                        width: 285
                    },
                    {
                        xtype: 'fieldset',
                        id: 'questionContainer',
                        title: 'Bla bla bla bla bla bla bla?',
                        items: [
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans1',
                                label: ' 2000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans2',
                                label: ' 9000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans3',
                                label: ' 20000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans4',
                                label: ' 800000',
                                labelWidth: 200
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                maxWidth: '',
                                width: 100,
                                text: '<'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                maxWidth: '',
                                width: 100,
                                text: '>'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                id: 'question5Panel',
                items: [
                    {
                        xtype: 'label',
                        height: 70,
                        html: 'Spørsmål 1',
                        id: 'questionTitle',
                        styleHtmlContent: true,
                        ui: 'light',
                        width: 285
                    },
                    {
                        xtype: 'fieldset',
                        id: 'questionContainer',
                        title: 'Bla bla bla bla bla bla bla?',
                        items: [
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans1',
                                label: ' 2000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans2',
                                label: ' 9000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans3',
                                label: ' 20000',
                                labelWidth: 200
                            },
                            {
                                xtype: 'radiofield',
                                html: '',
                                id: 'ans4',
                                label: ' 800000',
                                labelWidth: 200
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                maxWidth: '',
                                width: 100,
                                text: '<'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                maxWidth: '',
                                width: 100,
                                text: '>'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'submissionPanel',
                items: [
                    {
                        xtype: 'actionsheet',
                        hidden: true,
                        id: 'submiissionSheet',
                        items: [
                            {
                                xtype: 'button',
                                id: 'submit',
                                text: 'Send inn'
                            }
                        ]
                    },
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        id: 'titleBar'
                    },
                    {
                        xtype: 'fieldset',
                        height: 169,
                        id: 'infoFields',
                        title: 'Informasjon',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'nameField',
                                label: 'Navn'
                            },
                            {
                                xtype: 'emailfield',
                                id: 'mailField',
                                label: 'Epost',
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'numberfield',
                                id: 'tlfField',
                                label: 'Telefon'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});