/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        id: 'titlePage',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'titleBar',
                title: 'Steria Quiz'
            },
            {
                xtype: 'container',
                centered: true,
                height: 221,
                html: '<a href="#" onClick="Ext.create(\'MyApp.view.MyCarousel\', {fullscreen: true});"><img src="sterialogo.gif"></a>',
                id: 'logoContainer',
                width: 184,
                hideOnMaskTap: false
            }
        ]
    }

});